YABS-Version: 1

Projects:
  - Name: YABS
    Variables:
      - SourceDir: Source/
      - ObjectDir: Build/Objects/
      - Libraries: stdc++fs yaml-cpp
      - Binary: Build/yabs
      - C++Flags: -Wall -Wextra -IInclude -std=c++14
      - LinkFlags: -LLibrary

Configurations:
  - Name: Debug
    Variables:
      - C++Flags: -g -DDEBUG

Targets:
  - Name: Build
    Commands:
      - Tool: C++ Compile($C++Flags, +Find($SourceDir, *.cpp), $ObjectDir)
      - Tool: C++ Link($LinkFlags, +Find($ObjectDir, *.o), $Libraries, $Binary)

  - Name: Clean
    Commands:
      - Tool: Path Delete($ObjectDir $Binary)

  - Name: Rebuild
    Dependencies:
      - Clean
      - Build
