###############################################################################
# Workspace                                                                   #
###############################################################################
Name: BTool

###############################################################################
# Output File Layout                                                          #
###############################################################################
Output:
  Objects: Build/Objects/%(ARCH)/%(CONFIG)/%(PROJECT)/%(OBJECT)
  Binaries: Build/Binaries/%(ARCH)/%(CONFIG)/%(PROJECT)

###############################################################################
# Global Options                                                              #
###############################################################################
Flags:
  C++: -Wall -Wextra -IInclude -std=c++14
  Linker: -LLibrary -lyaml-cpp -lstdc++fs

###############################################################################
# Architecture-Specific Options                                               #
###############################################################################
Architectures:
  - Name: Native
    Tools:
      - Name: C++
        Toolchain: GCC
        Command: g++
      - Name: Linker
        Toolchain: GCC
        Command: g++

###############################################################################
# Configuration-Specific Options                                              #
###############################################################################
Configurations:
  - Name: Debug
    Flags:
      C++: -g -DDEBUG

###############################################################################
# Project-Specific Options                                                    #
###############################################################################
Projects:
  - Name: BTool
    Files:
      Sources:
        - Source
