YABS-Version: 1

Projects:
  - Name: YABS
    Variables:
      - SourceDir: Source
      - BinaryDir: Build
      - ObjectDir: $BinaryDir/Objects
      - Libraries: stdc++fs yaml-cpp
      - Binary: $BinaryDir/yabs
      - C++Flags: -Wall -Wextra -IInclude -std=c++14
      - LinkFlags: -LLibrary

Configurations:
  - Name: Debug
    Variables:
      - C++Flags: -g -DDEBUG

Targets:
  - Name: Build
    Commands:
      - Tool: C++ Compile($C++Flags, +Find($SourceDir, *.cpp), $ObjectDir)
      - Tool: C++ Link($LinkFlags, +Find($ObjectDir, *.o), $Libraries, $Binary)

  - Name: Clean
    Commands:
      - Tool: Path Delete($BinaryDir)

  - Name: Rebuild
    Dependencies:
      - Clean
      - Build

  - Name: Install
    Dependencies:
      - Build
    Commands:
      - Shell: cp $Binary /usr/local/bin/YABS_BINARY
      - Shell: cp -ar .yabs /etc/yabs
      - Shell: mv /usr/local/bin/YABS_BINARY /usr/local/bin/yabs